name: Check Release Version Change

on:
  pull_request:
    paths:
      - 'releaseVersion.txt'
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-release-version-change:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR URL
        run: |
          echo "The PR URL is ${{ github.event.pull_request.html_url }}"
