name: Check Release Version Change

on:
  pull_request:
    paths:
      - 'releaseVersion.txt'
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-release-version-change:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR URL
        run: |
          echo "PR URL: https://github.com/$GITHUB_REPOSITORY/pull/$GITHUB_RUN_ID"
