name: Check Release Version Change

on:
  pull_request:
    paths:
      - 'releaseVersion.txt'
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-release-version-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for release version change
        id: check-release-version
        run: |
          echo "Hello"
